const url = "https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt";
console.log("Fetching EFF large wordlist from:", url);

try {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch: ${response.statusText}`);
  }
  const text = await response.text();
  const lines = text.split("\n");
  const words: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const parts = trimmed.split(/\s+/);
    if (parts.length >= 2) {
      const word = parts[1].toLowerCase();
      if (/^[a-z]+$/.test(word)) {
        words.push(word);
      }
    }
  }

  console.log(`Successfully fetched and filtered ${words.length} words.`);

  const content =
    `// This file is auto-generated by fetch_wordlist.ts. Do not edit manually.
export const wordlist: string[] = ${JSON.stringify(words, null, 2)};
`;

  await Deno.writeTextFile("./src/shared/wordlist.ts", content);
  console.log("Saved to ./src/shared/wordlist.ts");
} catch (error) {
  console.error("Error fetching wordlist:", error);
}
