const RAW_URL =
  "https://raw.githubusercontent.com/duyet/vietnamese-wordlist/master/Viet74K.txt";

function removeVietnameseAccents(str: string): string {
  return str
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .replace(/ð/g, "d");
}

console.log("Fetching Viet74K.txt from:", RAW_URL);

try {
  const response = await fetch(RAW_URL);
  if (!response.ok) {
    throw new Error(`HTTP Error ${response.status}: ${response.statusText}`);
  }

  const text = await response.text();
  const lines = text.split(/\r?\n/);
  const wordSet = new Set<string>();

  for (const line of lines) {
    const raw = line.trim();
    if (!raw) continue;

    // Remove diacritics / accents, convert to lowercase, keep only a-z
    const noAccents = removeVietnameseAccents(raw).toLowerCase();
    const cleanWord = noAccents.replace(/[^a-z]/g, "");

    if (cleanWord.length >= 2) {
      wordSet.add(cleanWord);
    }
  }

  const sortedWords = Array.from(wordSet).sort();
  console.log(
    `Successfully fetched, processed accents, cleaned and deduplicated: ${sortedWords.length} unique words.`,
  );

  const fileContent =
    `// This file is auto-generated by scripts/fetch_vietnamese_wordlist.ts. Do not edit manually.
export const VIETNAMESE_WORDLIST: string[] = ${
      JSON.stringify(sortedWords, null, 2)
    };
`;

  const targetPath = "./packages/domain/src/vietnamese-wordlist.ts";
  await Deno.writeTextFile(targetPath, fileContent);
  console.log(`Successfully written to ${targetPath}`);
} catch (err) {
  console.error("Failed to process Vietnamese wordlist:", err);
}
